import type { Metadata } from "next";

import "../styles/global.css";
import {Footer, Header} from "@/entities";
import type { ReactNode } from "react";

export const metadata: Metadata = {
  title: "Cambridge Cangaroos",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
      <Header />
        <main>{children}</main>
      <Footer />
      </body>
    </html>
  );
}
